"""Type stubs for optipricer._core C++ extension module."""

from typing import List

def norm_cdf(x: float) -> float:
    """Standard normal cumulative distribution function."""
    ...

def norm_pdf(x: float) -> float:
    """Standard normal probability density function."""
    ...


class models:
    class BlackScholesModel:
        def __init__(
            self,
            strike_price: float,
            volatility: float,
            risk_free_rate: float,
            time_to_maturity: float,
            underlying_price: float,
            dividend_yield: float = 0.0,
        ) -> None: ...
        def d1(self) -> float: ...
        def d2(self) -> float: ...
        def call_price(self) -> float: ...
        def put_price(self) -> float: ...
        def get_strike_price(self) -> float: ...
        def get_volatility(self) -> float: ...
        def get_risk_free_rate(self) -> float: ...
        def get_time_to_maturity(self) -> float: ...
        def get_underlying_price(self) -> float: ...
        def get_dividend_yield(self) -> float: ...
        def __repr__(self) -> str: ...

    class GreeksCalculator:
        def __init__(self, model: 'models.BlackScholesModel') -> None: ...
        def get_model(self) -> 'models.BlackScholesModel': ...
        # First-order Greeks
        def call_delta(self) -> float: ...
        def put_delta(self) -> float: ...
        def gamma(self) -> float: ...
        def vega(self) -> float: ...
        def call_theta(self) -> float: ...
        def put_theta(self) -> float: ...
        def call_rho(self) -> float: ...
        def put_rho(self) -> float: ...
        # Second-order Greeks
        def vanna(self) -> float: ...
        def volga(self) -> float: ...
        def call_charm(self) -> float: ...
        def put_charm(self) -> float: ...
        def __repr__(self) -> str: ...

    @staticmethod
    def calculate_implied_volatility(
        market_price: float,
        strike_price: float,
        risk_free_rate: float,
        time_to_maturity: float,
        underlying_price: float,
        dividend_yield: float = 0.0,
        is_call: bool = True,
        tol: float = 1e-6,
        max_iter: int = 100,
    ) -> float: ...


class strategies:
    class OptionType:
        CALL: 'strategies.OptionType'
        PUT: 'strategies.OptionType'

    class PositionType:
        LONG: 'strategies.PositionType'
        SHORT: 'strategies.PositionType'

    class Position:
        option_type: 'strategies.OptionType'
        position_type: 'strategies.PositionType'
        quantity: float
        strike: float
        def __init__(
            self,
            option_type: 'strategies.OptionType',
            position_type: 'strategies.PositionType',
            quantity: float,
            strike: float,
        ) -> None: ...
        def __repr__(self) -> str: ...

    class OptionsStrategy:
        def __init__(
            self,
            underlying_price: float,
            volatility: float,
            risk_free_rate: float,
            time_to_maturity: float,
            strategy_name: str,
            dividend_yield: float = 0.0,
        ) -> None: ...
        def add_position(
            self,
            option_type: 'strategies.OptionType',
            position_type: 'strategies.PositionType',
            quantity: float,
            strike: float,
        ) -> None: ...
        def total_value(self) -> float: ...
        def total_delta(self) -> float: ...
        def total_gamma(self) -> float: ...
        def total_vega(self) -> float: ...
        def total_theta(self) -> float: ...
        def total_rho(self) -> float: ...
        def total_vanna(self) -> float: ...
        def total_volga(self) -> float: ...
        def total_charm(self) -> float: ...
        def payoff_at_expiration(self, underlying_price: float) -> float: ...
        def get_positions(self) -> List['strategies.Position']: ...
        def get_name(self) -> str: ...
        def get_dividend_yield(self) -> float: ...
        def __repr__(self) -> str: ...

    class LongCall(OptionsStrategy):
        def __init__(self, underlying_price: float, volatility: float, risk_free_rate: float, time_to_maturity: float, strike: float, quantity: float = 1.0, dividend_yield: float = 0.0) -> None: ...

    class ShortCall(OptionsStrategy):
        def __init__(self, underlying_price: float, volatility: float, risk_free_rate: float, time_to_maturity: float, strike: float, quantity: float = 1.0, dividend_yield: float = 0.0) -> None: ...

    class LongPut(OptionsStrategy):
        def __init__(self, underlying_price: float, volatility: float, risk_free_rate: float, time_to_maturity: float, strike: float, quantity: float = 1.0, dividend_yield: float = 0.0) -> None: ...

    class ShortPut(OptionsStrategy):
        def __init__(self, underlying_price: float, volatility: float, risk_free_rate: float, time_to_maturity: float, strike: float, quantity: float = 1.0, dividend_yield: float = 0.0) -> None: ...

    class LongStraddle(OptionsStrategy):
        def __init__(self, underlying_price: float, volatility: float, risk_free_rate: float, time_to_maturity: float, strike: float, quantity: float = 1.0, dividend_yield: float = 0.0) -> None: ...

    class ShortStraddle(OptionsStrategy):
        def __init__(self, underlying_price: float, volatility: float, risk_free_rate: float, time_to_maturity: float, strike: float, quantity: float = 1.0, dividend_yield: float = 0.0) -> None: ...

    class LongStrangle(OptionsStrategy):
        def __init__(self, underlying_price: float, volatility: float, risk_free_rate: float, time_to_maturity: float, put_strike: float, call_strike: float, quantity: float = 1.0, dividend_yield: float = 0.0) -> None: ...

    class ShortStrangle(OptionsStrategy):
        def __init__(self, underlying_price: float, volatility: float, risk_free_rate: float, time_to_maturity: float, put_strike: float, call_strike: float, quantity: float = 1.0, dividend_yield: float = 0.0) -> None: ...
